name: My First GitHub Action

on:
  push:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Show Python Version
        run: python --version

      - name: Show Current Directory
        run: pwd

      - name: List Repository Files
        run: ls -la

      - name: Run Python Program
        run: python app.py